/**
 * Unit tests for PDF Header/Footer functionality
 */

const PDFReportGenerator = require('../src/utils/pdf-report-generator');
const PDFThemeEngine = require('../src/utils/pdf-theme-engine');
const { PDFDocument } = require('pdf-lib');

describe('PDF Header/Footer Enhancement', () => {
  let pdfGenerator;
  let themeEngine;
  let mockPage;

  beforeEach(async () => {
    themeEngine = new PDFThemeEngine();
    pdfGenerator = new PDFReportGenerator({}, themeEngine);
    pdfGenerator.pdfDoc = await PDFDocument.create();
    pdfGenerator.helvetica = await pdfGenerator.pdfDoc.embedFont('Helvetica');
    pdfGenerator.helveticaBold = await pdfGenerator.pdfDoc.embedFont('Helvetica-Bold');
    pdfGenerator.setupColors();

    // Create a mock page for testing
    mockPage = pdfGenerator.pdfDoc.addPage();
    pdfGenerator.currentPage = mockPage;
    pdfGenerator.currentPageNumber = 1;
  });

  describe('Theme Integration', () => {
    test('uses theme engine for colors and fonts', () => {
      expect(pdfGenerator.themeEngine).toBe(themeEngine);
      expect(pdfGenerator.colors.primary).toBeDefined();
      expect(pdfGenerator.colors.secondary).toBeDefined();
      expect(pdfGenerator.colors.text).toBeDefined();
    });

    test('theme margins override config margins', () => {
      const margins = themeEngine.getMargins();
      expect(pdfGenerator.margin).toBe(margins.left);
    });
  });

  describe('Header Rendering', () => {
    test('drawHeader renders company branding on left', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawHeader('test-job-123');

      // Check that company name is rendered
      const branding = themeEngine.getBranding();
      expect(spy).toHaveBeenCalledWith(
        branding.companyName,
        expect.objectContaining({
          x: pdfGenerator.margin,
          size: themeEngine.getFontSize('body'),
          font: pdfGenerator.helveticaBold
        })
      );
    });

    test('drawHeader renders report title in center', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawHeader('test-job-123');

      expect(spy).toHaveBeenCalledWith(
        'Invoice Processing Report',
        expect.objectContaining({
          size: themeEngine.getFontSize('h3'),
          font: pdfGenerator.helveticaBold
        })
      );
    });

    test('drawHeader renders page number on right', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawHeader('test-job-123');

      expect(spy).toHaveBeenCalledWith(
        'Page 1',
        expect.objectContaining({
          size: themeEngine.getFontSize('caption'),
          font: pdfGenerator.helvetica
        })
      );
    });

    test('drawHeader includes divider line', () => {
      const spy = jest.spyOn(mockPage, 'drawLine');
      pdfGenerator.drawHeader('test-job-123');

      expect(spy).toHaveBeenCalledWith(
        expect.objectContaining({
          thickness: 0.5,
          color: pdfGenerator.colors.textLight
        })
      );
    });
  });

  describe('Footer Rendering', () => {
    test('drawFooter renders company generation info on left', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawFooter();

      const branding = themeEngine.getBranding();
      expect(spy).toHaveBeenCalledWith(
        `Generated by ${branding.companyName}`,
        expect.objectContaining({
          x: pdfGenerator.margin,
          size: themeEngine.getFontSize('caption')
        })
      );
    });

    test('drawFooter renders confidentiality notice in center', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawFooter();

      expect(spy).toHaveBeenCalledWith(
        'Confidential - For Internal Use Only',
        expect.objectContaining({
          size: themeEngine.getFontSize('caption')
        })
      );
    });

    test('drawFooter renders page numbering on right', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.totalPages = 5;
      pdfGenerator.drawFooter();

      expect(spy).toHaveBeenCalledWith(
        'Page 1 of 5',
        expect.objectContaining({
          size: themeEngine.getFontSize('caption')
        })
      );
    });

    test('drawFooter includes divider line', () => {
      const spy = jest.spyOn(mockPage, 'drawLine');
      pdfGenerator.drawFooter();

      expect(spy).toHaveBeenCalledWith(
        expect.objectContaining({
          thickness: 0.5,
          color: pdfGenerator.colors.textLight
        })
      );
    });
  });

  describe('Page Management', () => {
    test('addNewPage increments page counter', () => {
      const initialPageCount = pdfGenerator.pdfDoc.getPageCount();
      pdfGenerator.addNewPage('test-job');
      expect(pdfGenerator.currentPageNumber).toBe(initialPageCount + 1);
    });

    test('addNewPage sets correct Y position with theme margins', () => {
      pdfGenerator.addNewPage('test-job');
      const headerHeight = themeEngine.getFontSize('h3') + 10; // Header height + spacing
      const expectedY = pdfGenerator.pageHeight - pdfGenerator.margin - headerHeight;
      expect(pdfGenerator.yPosition).toBe(expectedY);
    });

    test('updateAllPageFooters sets correct total pages', () => {
      // Add a few pages
      pdfGenerator.addNewPage('test-job');
      pdfGenerator.addNewPage('test-job');
      pdfGenerator.addNewPage('test-job');

      pdfGenerator.updateAllPageFooters();
      expect(pdfGenerator.totalPages).toBe(4); // 3 new pages + 1 initial page
    });
  });

  describe('Page Space Checking', () => {
    test('checkPageSpace adds new page when space is insufficient', () => {
      const addNewPageSpy = jest.spyOn(pdfGenerator, 'addNewPage');
      const drawFooterSpy = jest.spyOn(pdfGenerator, 'drawFooter');

      // Set Y position near bottom
      pdfGenerator.yPosition = pdfGenerator.margin + 50;

      const needsNewPage = pdfGenerator.checkPageSpace(100);

      expect(needsNewPage).toBe(true);
      expect(drawFooterSpy).toHaveBeenCalled();
      expect(addNewPageSpy).toHaveBeenCalled();
    });

    test('checkPageSpace returns false when space is sufficient', () => {
      const addNewPageSpy = jest.spyOn(pdfGenerator, 'addNewPage');

      // Set Y position with plenty of space
      pdfGenerator.yPosition = pdfGenerator.pageHeight - 200;

      const needsNewPage = pdfGenerator.checkPageSpace(50);

      expect(needsNewPage).toBe(false);
      expect(addNewPageSpy).not.toHaveBeenCalled();
    });
  });

  describe('Typography Integration', () => {
    test('drawText uses theme-based font sizes by default', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawText('Test text', 100, 200);

      expect(spy).toHaveBeenCalledWith(
        'Test text',
        expect.objectContaining({
          size: themeEngine.getFontSize('body')
        })
      );
    });

    test('drawText allows custom font size override', () => {
      const spy = jest.spyOn(mockPage, 'drawText');
      pdfGenerator.drawText('Test text', 100, 200, { size: 18 });

      expect(spy).toHaveBeenCalledWith(
        'Test text',
        expect.objectContaining({
          size: 18
        })
      );
    });
  });
});